### ISSUE TITLE
Is supporting extends construct in the pipeline?

### ISSUE THREAD

**Issue by jsaimani** [jlblcc/json-schema-viewer#3]
This is a fantastic tool. Would love to use it, but our schema extensively use the extends attribute of json schema to enforce inheritance kind of relationships.

**Comment by jlblcc** [comment]
Sorry, there aren't any plans to support json schema drafts prior to v4. Since the viewer uses the tv4 library to fetch and compile the schemas, only draft v4 is being supported for validations. The 'extends' keyword was [removed in draft v4](https://github.com/json-schema/json-schema/wiki/anyOf,-allOf,-oneOf,-not).
